server: 
  port: 3344 
  
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/FlynnCN/microservicecloud-config.git #GitHub上面的git仓库名字
          username: FlynnCN
          password: cfliang123
          force-pull: true
 
